export const token = [
    {
      name: 'Vulkania',
      symbol: 'VLK',
      logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      contract: '0x0921...2cb87',
      Blockchain: 'ethereum',
      BlockchainLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      State: 'Research',
      Rating: 5,
      Price: 0.1334899,
      PriceChange: 10,
      MarketCap: 2669376,
      id: "alvgf5",
      TokenStandard: 'BEP20',
      Mintable: false,
      Decimals: '2',
      CirculatingSupply: '220',
      TotalSupply: '240',
      TotalTaxes: '9',
      Dividends: '5',
      PresalePrice: '2',
      LaunchPrice: '5',
      PresaleDate: new Date(),
      LaunchDate: new Date(),
      MinSlipPage: '11',
      MaxSlipPage: '12'
    },
    {
      name: 'Vulkania',
      symbol: 'VLK',
      logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      contract: '0x0921...2dl88',
      Blockchain: 'ethereum',
      BlockchainLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      State: 'Watchlist',
      Rating: 4,
      Price: 0.1334899,
      PriceChange: 10,
      MarketCap: 2669376,
      id: "497gkdf",
      TokenStandard: 'BEP20',
      Mintable: false,
      Decimals: '2',
      CirculatingSupply: '220',
      TotalSupply: '240',
  
      TotalTaxes: '9',
      Dividends: '5',
      PresalePrice: '2',
      LaunchPrice: '5',
      PresaleDate: new Date(),
      LaunchDate: new Date(),
      MinSlipPage: '11',
      MaxSlipPage: '12'
    },
    {
      name: 'Vulkania',
      symbol: 'VLK',
      logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      contract: '0x0921...2dk89',
      Blockchain: 'Bitcoin',
      BlockchainLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      State: 'New',
      Rating: 3,
      Price: 0.1334899,
      PriceChange: 10,
      MarketCap: 2669376,
      id: "4967gj",
      TokenStandard: 'BEP20',
      Mintable: false,
      Decimals: '2',
      CirculatingSupply: '220',
      TotalSupply: '240',
  
      TotalTaxes: '9',
      Dividends: '5',
      PresalePrice: '2',
      LaunchPrice: '5',
      PresaleDate: new Date(),
      LaunchDate: new Date(),
      MinSlipPage: '11',
      MaxSlipPage: '12'
    },
    {
      name: 'Vulkania',
      symbol: 'VLK',
      logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      contract: '0x0921...1db90',
      Blockchain: 'ethereum',
      BlockchainLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      State: 'Research',
      Rating: 2,
      Price: 0.1334899,
      PriceChange: 10,
      MarketCap: 2669376,
      id: "96db64",
      TokenStandard: 'BEP20',
      Mintable: false,
      Decimals: '2',
      CirculatingSupply: '220',
      TotalSupply: '240',
  
      TotalTaxes: '9',
      Dividends: '5',
      PresalePrice: '2',
      LaunchPrice: '5',
      PresaleDate: new Date(),
      LaunchDate: new Date(),
      MinSlipPage: '11',
      MaxSlipPage: '12'
    },
    {
      name: 'Vulkania',
      symbol: 'VLK',
      logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      contract: '0x0921...2db81',
      Blockchain: 'BitCoin',
      BlockchainLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      State: 'Research',
      Rating: 1,
      Price: 0.1334899,
      PriceChange: -10,
      MarketCap: 2669376,
      id: "396hvf",
      TokenStandard: 'BEP20',
      Mintable: false,
      Decimals: '2',
      CirculatingSupply: '220',
      TotalSupply: '240',
  
      TotalTaxes: '9',
      Dividends: '5',
      PresalePrice: '2',
      LaunchPrice: '5',
      PresaleDate: new Date(),
      LaunchDate: new Date(),
      MinSlipPage: '11',
      MaxSlipPage: '12'
    },
    {
      name: 'Vulkania',
      symbol: 'VLK',
      logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      contract: '0x0921...2db99',
      Blockchain: 'Bitcoin',
      BlockchainLogo:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgolBdeaXdt7hZ4G28YiA8shOCg4jkBg08uA&usqp=CAU',
      State: 'Watchlist',
      Rating: 0,
      Price: 0.1334899,
      PriceChange: 10,
      MarketCap: 2669376,
      id: "397hcvg",
      TokenStandard: 'BEP20',
      Mintable: false,
      Decimals: '2',
      CirculatingSupply: '220',
      TotalSupply: '240',
  
      TotalTaxes: '9',
      Dividends: '5',
      PresalePrice: '2',
      LaunchPrice: '5',
      PresaleDate: new Date(),
      LaunchDate: new Date(),
      MinSlipPage: '11',
      MaxSlipPage: '12'
    }
  ];
  export const headings = [
    'Name',
    'Symbol',
    'Logo',
    'Contract',
    'BlockChain',
    'BlockchainLogo',
    'State',
    'Rating',
    'Price',
    'PriceChange',
    'MarketCap'
  ];